id: A2B1BB825
title: A Short Supplication to Tārā
type: translation
pechas:
- I5A905908
- I6B63EC06
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:20.808204
  last_modified_at: 2023-01-04 12:01:20.808211
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I5A905908/DA0F: 1C84
  I6B63EC06/7EF7: 1C84
